version: 0.2

env:
    variables:
        PROJECT_NAME: infrastructure
        BUCKET_NAME: factory-ci-cd
        S3_LAMBDAS_DESTINATION: applications/lambda
        LAMBDAS_SOURCE_FOLDER: lambda_functions
        CICD_FUNCTIONS_SOURCE_DIR: structure/functions
        S3_CICD_FUNCTIONS_DESTINATION: applications/cicd/functions
        CICD_TOOLS_VERSION: 1.0.1

phases: 
    install:
        runtime-versions:
            python: 3.11
        commands:
            - apt update -y
            - pip install twine
            - pip install build
    pre_build:
        commands:
            - echo "Pre build commands ..."
            - aws codeartifact login --tool twine --domain factory --domain-owner 781648067507 --repository FactoryRepository --region eu-central-1
    build:
        commands:
            - echo "Building infrastructure ..."
            - echo "Uploading structure files ..."
            - python3 update_structure_files.py
            - echo Updating common packages
            - python3 -m build ./structure/libraries/cicd_tools/ --outdir .
            - twine upload --repository codeartifact cicd_tools-${CICD_TOOLS_VERSION}.tar.gz
    post_build:
        commands:
            - echo "Post build commands  ..."
cache:
    paths:
        - '/root/.m2/**/*'
        - '/root/.npm/**/*'
        - '/root/.pip-cache/**/*'
        - '/root/.docker/**'